config/routes.rb
Odb::Application.routes.draw do
  root to: 'static#home'
  resources :opportunities
  match 'auth/:provider/callback', to: 'sessions#create', via: 'get'
  match 'auth/failure', to: redirect('/'), via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/subscribe', to: 'static#subscribe', via: 'get'

  # The priofoority is based upon order of creation:
  # first created -> highest priority.

  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  # root :to => 'welcome#index'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/models/opportunity.rb
class Opportunity < ActiveRecord::Base
    belongs_to :user
    default_scope -> { order('created_at DESC') }

    scope :track,  ->(track)  { where(track: track.downcase)         }
    scope :city,   ->(city)   { where(location: city.downcase)       }
    scope :salary, ->(salary) { where("salary_low > ?", salary*1000) }

    before_save {
        downcase(:location=, self.location)
        downcase(:position=, self.position)
        downcase(:company=, self.company)
        downcase(:link=, self.link)
    }

    validates :user_id, :position, :company, :location, :track, presence: true

    validates :track, inclusion: { in: %w{dev sales product marketing}, 
        message: "%{value} is not a valid track" }

    validates :salary_low, :salary_high, numericality: true, presence: true

    private

    def downcase(setter, arg='')
        self.send(setter, arg.downcase! || arg)
    end
end
#--
# generated by 'annotated-rails' gem, please do not remove this line and content below, instead use `bundle exec annotate-rails -d` command
#++
# Table name: opportunities
#
# * id          :integer         not null
#   position    :string(255)
#   company     :string(255)
#   location    :string(255)
#   contact     :string(255)
#   link        :text(255)
#   created_at  :datetime
#   updated_at  :datetime
#   track       :string(255)
#   user_id     :integer
#   notes       :text(255)
#   salary_low  :integer
#   salary_high :integer
#--
# generated by 'annotated-rails' gem, please do not remove this line and content above, instead use `bundle exec annotate-rails -d` command
#++

app/models/user.rb
class User < ActiveRecord::Base
    has_many :opportunities
    
    def self.from_omniauth(auth)
        where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
            user.provider = auth.provider
            user.uid = auth.uid
            user.name = auth.info.name
            user.email = auth.info.email
            user.url = auth.info.urls[:Facebook]
            user.img_url = auth.info.image
            user.oath_token = auth.credentials.oath_token
            user.oath_expires_at = Time.at(auth.credentials.expires_at)
            user.save!
        end
    end
end
#--
# generated by 'annotated-rails' gem, please do not remove this line and content below, instead use `bundle exec annotate-rails -d` command
#++
# Table name: users
#
# * id              :integer         not null
#   uid             :string(255)
#   name            :string(255)
#   email           :string(255)
#   img_url         :string(255)
#   oath_token      :string(255)
#   oath_expires_at :datetime
#   created_at      :datetime
#   updated_at      :datetime
#   provider        :string(255)
#   url             :string(255)
#--
# generated by 'annotated-rails' gem, please do not remove this line and content above, instead use `bundle exec annotate-rails -d` command
#++

app/controllers/application_controller.rb
include SessionsHelper

class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/opportunities_controller.rb
class OpportunitiesController < ApplicationController
    before_filter :correct_user, only: [:edit, :update]
    has_scope :track
    has_scope :city
    has_scope :salary

  def new
    @opportunity = Opportunity.new
  end

  def create
    @opportunity = Opportunity.create(opportunity_params)
    @opportunity.user_id = current_user.id
    if @opportunity.save
      flash[:success] = "Thanks for sharing!"
      redirect_to @opportunity
    else
      render 'new'
    end
  end

  def edit
    @opportunity = Opportunity.find(params[:id])
  end

  def update
    @opportunity = Opportunity.find(params[:id])
    if @opportunity.update_attributes(opportunity_params)
      flash[:success] = "Opportunity updated"
      redirect_to opportunities_path
    else
      render 'edit'
    end
  end

  def index
    query = Opportunity.scoped
    query = query.track(params[:track]) if params[:track]
    query = query.city(params[:city]) if params[:city]
    query = query.salary(params[:salary].to_i) if params[:salary]
    @opportunities = query.all

    respond_to do |format|
      format.html
      format.json { render :json => @opportunities }
    end
  end

  def show
    @opportunity = Opportunity.find(params[:id])
    @user = User.find(@opportunity.user_id)
  end

  def destroy
    Opportunity.find(params[:id]).destroy
    flash[:success] = "Opportunity deleted."
    redirect_to opportunities_path
  end

  private
    def opportunity_params
        params.require(:opportunity).permit(:position, :track, :company, :location, :salary_low, :salary_high, :contact, :link, :notes)
    end

    def correct_user
      opportunity = Opportunity.find(params[:id])
      redirect_to(opportunities_path) unless current_user?(opportunity.user_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_url
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
  end

  def subscribe
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/opportunities_helper.rb
module OpportunitiesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user?(user_id)
    user_id == current_user.id
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
    <div class="container">
        <small>
            Powered by milk tea.
        </small>
        <nav>
        <ul>
          <li><%= link_to "the Institute",   "http://www.startupinstitute.com/" %></li>
          <li><%= link_to "Talk to me", "http://j4p3.com" %></li>
          <li><%= link_to "Contribute", "http://github.com/bonnerjp/opportunitydatabase" %></li>
        </ul>
        </nav>
    </div>
</footer>

app/views/layouts/_header.html.erb
<div class="navbar">
  <div class="container">
    <%= link_to "SI ODB", root_path, {class: "navbar-brand"}%>
    <ul class="nav navbar-nav">
      <li class="active"><% link_to "Home", root_path %></li>
      <li><%= link_to "Share an Opportunity", new_opportunity_path %></li>
      <li><%= link_to "Find an Opportunity", opportunities_path %></li>
      <li><%= link_to "Subscribe for Opportunities", subscribe_path %></li>
    </ul>
    <% if current_user %>
    <ul class="nav navbar-nav pull-right">
        <li><img src=<%= current_user.img_url %>></li>
        <li><%= link_to "Sign Out", signout_path, method: :delete %></li>
    </ul>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SI ODB</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
    <%= render 'layouts/header' %>
    <div class="container main">
        <% flash.each do |key, value| %>
            <%= content_tag(:div, value, class: "alert alert-#{key}") %>
        <% end %>
        <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
</body>
</html>

app/views/opportunities/_filter.html.erb
<section class="filters clearfix">
    <div class="filter well">
        <h4>Track:</h4>
        <ul class="nav nav-pills">
        <li class=<%= "active" if params[:track] == 'dev' %>><%= link_to 'Dev', opportunities_path(params.merge({track: 'dev'})) %></li>
        <li class=<%= 'active' if params[:track] == 'sales' %> ><%= link_to 'Sales', opportunities_path(params.merge({track: 'sales'})) %></li>
        <li class=<%= 'active' if params[:track] == 'marketing' %> ><%= link_to 'Marketing', opportunities_path(params.merge({track: 'marketing'})) %></li>
        <li class=<%= 'active' if params[:track] == 'product' %> ><%= link_to 'Product', opportunities_path(params.merge({track: 'product'})) %></li>
        <li class=<%= 'active' if params[:track] == nil %> ><%= link_to 'All', opportunities_path(params.merge({track: nil})) %></li>
    </ul>
    </div>
    <div class="filter well">
        <h4>City:</h4>
        <ul class="nav nav-pills">
            <li class=<%= 'active' if params[:city] == 'new york city' %> ><%= link_to 'NYC', opportunities_path(params.merge({city: 'new york city'})) %></li>
            <li class=<%= 'active' if params[:city] == 'boston' %> ><%= link_to 'BOS', opportunities_path(params.merge({city: 'boston'})) %></li>
            <li class=<%= 'active' if params[:city] == 'chicago' %> ><%= link_to 'CHI', opportunities_path(params.merge({city: 'chicago'})) %></li>
            <li class=<%= 'active' if params[:city] == nil %> ><%= link_to 'All', opportunities_path(params.merge({city: nil})) %></li>
        </ul>
    </div>
    <div class="filter well">
        <h4>Salary:</h4>
        <ul class="nav nav-pills">
            <li class=<%= 'active' if params[:salary] == '30' %> ><%= link_to '>30', opportunities_path(params.merge({salary: 30})) %></li>
            <li class=<%= 'active' if params[:salary] == '50' %> ><%= link_to '>50', opportunities_path(params.merge({salary: 50})) %></li>
            <li class=<%= 'active' if params[:salary] == '70' %> ><%= link_to '>70', opportunities_path(params.merge({salary: 70})) %></li>
            <li class=<%= 'active' if params[:salary] == '100' %> ><%= link_to '>100', opportunities_path(params.merge({salary: 100})) %></li>
            <li class=<%= 'active' if params[:salary] == nil %> ><%= link_to 'All', opportunities_path(params.merge({salary: nil})) %></li>
        </ul>
    </div>
</section>

app/views/opportunities/_opportunity.html.erb
<%= link_to opportunity, {class: "list-group-item opportunity"} do %>
    <h4 class="list-group-item-heading"><%= opportunity.position %></h4>
    <ul class="list-group-item-text">
        <li><%= opportunity.track.titleize %> - </li>
        <li><%= opportunity.company %> - </li>
        <li><%= opportunity.location.titleize %> - </li>
        <li>
          <% if opportunity.salary_low == opportunity.salary_high %>
            <% if opportunity.salary_low == 0 %>
              Salary not provided
            <% else %>
              $<%= opportunity.salary_low %>
            <% end %>
          <% else %>
            $<%= opportunity.salary_low %> - $<%= opportunity.salary_high %>
          <% end %>
        </li>
    </ul>
<% end %>

app/views/opportunities/destroy.html.erb
<h1>Opportunities#destroy</h1>
<p>Find me in app/views/opportunities/destroy.html.erb</p>

app/views/opportunities/edit.html.erb
<% provide(:title, "Edit opportunity") %> 
<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@opportunity) do |f| %>
    <div>
      <%= f.label :position %>
      <%= f.text_field :position %>
      </div>
      <div>
      <%= f.label :company %>
      <%= f.text_field :company %>
      </div>
      <div>
      <%= f.label :location %>
      <%= f.text_field :location %>
      </div>
      <div>
      <%= f.label :salary_low %>
      <%= f.text_field :salary_low %>
      </div>
      <div>
      <%= f.label :salary_high %>
      <%= f.text_field :salary_high %>
      </div>
      <div>
      <%= f.label :track %>
      <%= f.text_field :track %>
      </div>
      <div>
      <%= f.label :notes %>
      <%= f.text_field :notes %>
      </div>
      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>

  <%= link_to "Delete Opportunity", @opportunity, method: :delete, class: "btn btn-warning btn-large" %>
</div>

app/views/opportunities/index.html.erb
<h1>Opportunities</h1>
<section class="opportunities index list-group">
    <%= render 'opportunities/filter' %>
    <%= render @opportunities %>
</div>

app/views/opportunities/new.html.erb
<section class="opportunities new">
    <h1>Share an Opportunity</h1>
    <%= form_for(@opportunity) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
        <div class="input-group">
            <span class="input-group-addon input-large">Position</span>
            <%= f.text_field :position, {class: "form-control input-large", placeholder: "No ninjas or rockstars allowed."} %>
        </div>
        <div class="input-group">
            <div class="input-group-btn">
                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">Track <span class="caret"></span></button>
                <ul class="dropdown-menu">
                    <li><a href="#" data-content="dev" onclick="$('#track').val('dev');">Dev</a></li>
                    <li><a href="#" data-content="sales" onclick="$('#track').val('sales');">Sales</a></li>
                    <li><a href="#" data-content="product" onclick="$('#track').val('product');">Product</a></li>
                    <li><a href="#" data-content="marketing" onclick="$('#track').val('marketing');">Marketing</a></li>
                </ul>
            </div>
            <%= f.text_field :track, {class: "form-control", placeholder: "<- please use the button :)", id: "track"} %>
        </div>
        <div class="input-group">
            <span class="input-group-addon">Company</span>
            <%= f.text_field :company, {class: "form-control", placeholder: "Name of Company"} %>
        </div>
        <div class="input-group">
            <div class="input-group-btn">
                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">City <span class="caret"></span></button>
                <ul class="dropdown-menu">
                    <li><a href="#" data-content="Boston" onclick="$('#city').val('Boston');">Boston</a></li>
                    <li><a href="#" data-content="New York City" onclick="$('#city').val('New York City');">New York</a></li>
                    <li><a href="#" data-content="Chicago" onclick="$('#city').val('Chicago');">Chicago</a></li>
                    <li><a href="#" data-content="Any" onclick="$('#city').val('Any');">Other</a></li>
                </ul>
            </div>
            <%= f.text_field :location, {class: "form-control", placeholder: "<- please use the button :)", id: 'city'} %>
        </div>
        <div class="input-group">
            <span class="input-group-addon">Salary (Low)</span>
            <%= f.text_field :salary_low, {class: "form-control", placeholder: "e.g. 45,000"} %>
        </div>
        <div class="input-group">
            <span class="input-group-addon">Salary (High)</span>
            <%= f.text_field :salary_high, {class: "form-control", placeholder: "e.g. 55,000"} %>
        </div>
        <div class="input-group">
            <span class="input-group-addon">Contact</span>
            <%= f.text_field :contact, {class: "form-control", placeholder: "Who should the applicant get in touch with"} %>
        </div>
        <div class="input-group">
            <span class="input-group-addon">Link</span>
            <%= f.text_field :link, {class: "form-control", placeholder: "http://company-name.com/jobs"} %>
        </div>
        <div class="input-group">
            <span class="input-group-addon">Notes</span>
            <%= f.text_field :link, {class: "form-control", placeholder: "Anything else about this opportunity?"} %>
        </div>

        <%= f.submit "Post Opportunity", class: "btn btn-large btn-primary" %>
    <% end %>
</section>

app/views/opportunities/show.html.erb
<section class="panel opportunity show">
    <h1 class="panel-heading"><%= @opportunity.position %></h1>
    <ul>
        <li><b>Track: </b><%= @opportunity.track.titleize %></li>
        <li><b>Company: </b><%= @opportunity.company %></li>
        <li><b>Link: </b><%= @opportunity.link %></li>
        <li><b>Location: </b><%= @opportunity.location.titleize %></li>
        <li><b>Salary: </b><%= @opportunity.salary_low == @opportunity.salary_high ? "$#{@opportunity.salary_low}" : "$#{@opportunity.salary_low} - $#{@opportunity.salary_high}" %></li>
        <li><b>Posted: </b><%= @opportunity.created_at %></li>
        <li><b>Posted By: </b><%= link_to @user.name, @user.url %></li>
        <% if current_user?(@opportunity.user_id) %>
            <li>
            <%= link_to "Edit", edit_opportunity_path(@opportunity.id) %>
            </li>
        <% end %>
    </ul>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
<div id="error_explanation">
    <div class="alert alert-error">
        Sorry - we've got <%= pluralize(object.errors.count, "problem") %>.
        <ul>
            <% object.errors.full_messages.each do |msg| %>
            <li>* <%= msg %></li>
            <% end %>
        </ul>
    </div>
</div>
<% end %>